name: Security Scan
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday

jobs:
  security-scan:
    name: Security Scanning
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Run Trivy Vulnerability Scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH'

    - name: Upload Trivy Scan Results
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

    - name: Checkov Security Scan
      uses: bridgecrewio/checkov-action@master
      with:
        directory: .
        framework: terraform
        quiet: true
        skip_check: CKV_AWS_115,CKV_AWS_116

    - name: Snyk Security Scan
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --all-projects --sarif-file-output=snyk.sarif

    - name: Upload Snyk Results
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'snyk.sarif'

    - name: Pulumi Policy Scan
      run: |
        pip install pulumi-policy
        find . -name "Pulumi.yaml" -exec dirname {} \; | xargs -I {} pulumi policy enable --dir {}

    - name: CodeQL Analysis
      uses: github/codeql-action/init@v3
      with:
        languages: python, javascript

    - name: Autobuild
      uses: github/codeql-action/autobuild@v3

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3